/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CustomersAddCustomerRouteImport } from './routes/customers/add-customer'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as InvoicesIdRouteImport } from './routes/invoices/$id'
import { Route as InvoicesBuilderRouteImport } from './routes/invoices/builder'
import { Route as RecordsIndexRouteImport } from './routes/records/index'
import { Route as RecordsCreateRecordRouteImport } from './routes/records/create-record'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersAddCustomerRoute = CustomersAddCustomerRouteImport.update({
  id: '/customers/add-customer',
  path: '/customers/add-customer',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesBuilderRoute = InvoicesBuilderRouteImport.update({
  id: '/invoices/builder',
  path: '/invoices/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIndexRoute = RecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsCreateRecordRoute = RecordsCreateRecordRouteImport.update({
  id: '/records/create-record',
  path: '/records/create-record',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/items': typeof ItemsRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/customers/add-customer': typeof CustomersAddCustomerRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/builder': typeof InvoicesBuilderRoute
  '/records/create-record': typeof RecordsCreateRecordRoute
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/records/': typeof RecordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/items': typeof ItemsRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/customers/add-customer': typeof CustomersAddCustomerRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/builder': typeof InvoicesBuilderRoute
  '/records/create-record': typeof RecordsCreateRecordRoute
  '/customers': typeof CustomersIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/records': typeof RecordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/items': typeof ItemsRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/customers/add-customer': typeof CustomersAddCustomerRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/builder': typeof InvoicesBuilderRoute
  '/records/create-record': typeof RecordsCreateRecordRoute
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/records/': typeof RecordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/items'
    | '/pricing'
    | '/settings'
    | '/customers/add-customer'
    | '/invoices/$id'
    | '/invoices/builder'
    | '/records/create-record'
    | '/customers/'
    | '/invoices/'
    | '/records/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/items'
    | '/pricing'
    | '/settings'
    | '/customers/add-customer'
    | '/invoices/$id'
    | '/invoices/builder'
    | '/records/create-record'
    | '/customers'
    | '/invoices'
    | '/records'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/items'
    | '/pricing'
    | '/settings'
    | '/customers/add-customer'
    | '/invoices/$id'
    | '/invoices/builder'
    | '/records/create-record'
    | '/customers/'
    | '/invoices/'
    | '/records/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  ItemsRoute: typeof ItemsRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  CustomersAddCustomerRoute: typeof CustomersAddCustomerRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  InvoicesBuilderRoute: typeof InvoicesBuilderRoute
  RecordsCreateRecordRoute: typeof RecordsCreateRecordRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  RecordsIndexRoute: typeof RecordsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/add-customer': {
      id: '/customers/add-customer'
      path: '/customers/add-customer'
      fullPath: '/customers/add-customer'
      preLoaderRoute: typeof CustomersAddCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/builder': {
      id: '/invoices/builder'
      path: '/invoices/builder'
      fullPath: '/invoices/builder'
      preLoaderRoute: typeof InvoicesBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/': {
      id: '/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof RecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/create-record': {
      id: '/records/create-record'
      path: '/records/create-record'
      fullPath: '/records/create-record'
      preLoaderRoute: typeof RecordsCreateRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  ItemsRoute: ItemsRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  CustomersAddCustomerRoute: CustomersAddCustomerRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  InvoicesBuilderRoute: InvoicesBuilderRoute,
  RecordsCreateRecordRoute: RecordsCreateRecordRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  RecordsIndexRoute: RecordsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
